name: Laravel

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main, feature/** ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: peerfinder_test
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306:3306
        # Set health checks to wait until mysql database has started
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Tests
      run: php artisan test
    - name: Install and run node
      run: npm install && npm run production
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux &
    - name: Run Laravel Server
      run: php artisan serve --no-reload &
    - name: Run Dusk Tests
      env:
        APP_URL: "http://127.0.0.1:8000"
      run: php artisan dusk
    - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
    - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
